spring:
  application:
    name: reading-service

server:
  port: 8083

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

task-service:
  ribbon:
    eureka:
      enabled: true
    listOfServers: localhost:8082
    ServerListRefreshInterval: 15000