spring:
  application:
    name: gateway-service

server:
  port: 8084

eureka:
  instance:
    appname: gateway-service
  client:
    healthcheck:
      enabled: true
    enabled: true
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8888/eureka


zuul:
  routes:
    task-service:
      path: /api/task/**
      url: http://localhost:8082