spring:
  application:
    name: task-service

server:
  port: 8082

eureka:
  instance:
    appname: task-service
  client:
    healthcheck:
      enabled: true
    enabled: true
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8888/eureka