server:
  port: 8888

spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: 1

logging:
  level:
    org:
      springframework:
        security: DEBUG

eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0